env:
  browser: true
  es6: true
  jquery: true
extends: ['eslint:recommended']
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars: 
    - error
    - argsIgnorePattern: '[iI]gnored'
